### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by andy-innersource** [tolitius/cbass#11]
we also wonder if it would be possible to freeze and release new version of cbass.

**Comment by tolitius** [comment]
sure, `[cbass "0.2.1"]` is released with the latest commit

**Comment by andy-innersource** [comment]
I somehow missed it here https://github.com/tolitius/cbass/releases. It is important for us to be able to correlate exact source code revision.

**Comment by tolitius** [comment]
it's there: https://github.com/tolitius/cbass/releases (needed to be tagged)
but you can also see it by clicking on the version in README: https://clojars.org/cbass/versions/0.2.1

**Comment by andy-innersource** [comment]
big thanks
