### ISSUE TITLE
:auto not supported on headerless data. {}

### ISSUE THREAD

**Issue by ghost** [tolitius/cbass#6]
I got this error while scanning the data from hbase ( apache nutch data ) .

```
CompilerException clojure.lang.ExceptionInfo: :auto not supported on headerless data. {}, compiling```

**Comment by tolitius** [comment]
most likely you are trying to read data from HBase that was not written with `cbass`.

`cbass` uses [nippy](https://github.com/ptaoussanis/nippy) for serialization / deserialization by default. In case you are working with data that was not _written_ by `cbass`, you can change it:

```clojure
(def conn (new-connection conf :pack identity 
                               :unpack identity))
```

In this example `cbass` will not try to pack / unpack when it writes / reads data from HBase. You can of course substitute `identity` function above with your way of serializing / deserializing data to / from HBase.

more details in the [serialization section](https://github.com/tolitius/cbass#custom-serializers) of the docs.

**Comment by ghost** [comment]
@tolitius thanks.
